language: rust
rust:
  - stable
  - beta
  - 1.43.0
matrix:
  allow_failures:
    - rust: beta
cache: cargo

before_script:
  - rustup component add clippy rustfmt

script:
  - cargo update
  - cargo fmt
  - cargo fix
  - cargo fix
  - cargo build --release
  - cargo test
