[package]
name = "prometheusfmt"
version = "0.1.0"
authors = ["123shang60 <616761475@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus_exporter_base = "1.1.0"
psutil = "3.2.0"